### ISSUE TITLE
Upload picture: Refined UI

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#102]
1. Chose file button margin to left.
2. Show little preview of image before uploading.
3. Upload button on right, cancel on left.
4. Upload button should be bold (primary action).
<img width="269" alt="image" src="https://user-images.githubusercontent.com/5204169/42365965-3a4ba744-8100-11e8-8b4a-3dc30fcfdc80.png">

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/0e200674b3aa03f4fcae34e93af41ceea84e43f9
