### ISSUE TITLE
Cant comment because bar is stuck to bottom and i cant scroll

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#114]
<img width="718" alt="screen shot 2018-07-09 at 3 08 44 pm" src="https://user-images.githubusercontent.com/8992275/42473347-0586d790-838a-11e8-97ff-809ae44301bd.png">

**Comment by frogg** [comment]
Related: the "add comment" button is also hidden by the tool bar on the bottom:

<img width="1627" alt="image" src="https://user-images.githubusercontent.com/5204169/42626078-a31d3e40-85c9-11e8-884b-cd89079c3bcb.png">

**Comment by cocokiri** [comment]
somewhere some component is sett

**Comment by frogg** [comment]
So it works now?

**Comment by cocokiri** [comment]
Ok I fixed the overlay problem with the MobileStepper <Prev Next>.
There was some weird invisible distance between the rating component and the <Prev Next> Bar.
It's the overflow-x: hidden attribute ...so I couldn't possibly find it in the DOM Tree. Nasty.

![screen shot 2018-07-13 at 12 39 59 pm](https://user-images.githubusercontent.com/3579138/42687710-e8f149c2-8699-11e8-89fc-7a934262206a.png)

**Comment by cocokiri** [comment]
K found a way
