### ISSUE TITLE
Similar to google docs, we need unique URLs for editing

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#115]
When creating new content id123, I should be able to bookmark the website, so I can continue editing the content later via it's unique URL app.joinoasys.org/create/id123

**Comment by frogg** [comment]
What would happen if you send this link to a friend and you edit it at the same time? 😂

**Comment by dlrenz** [comment]
Well. I would say that we disallow others to edit my documents directly. So someone who is not the content creator should be forwarded either to 404 or ContentView!
