### ISSUE TITLE
Description/Hashtag in editor should be prefilled

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#122]
After hitting publish twice, user has to re-fill description and hashtags - the values that they had input the first time around do not show. Also, title is not editable (good), but should indicate so (greyed out?)

**Comment by frogg** [comment]
Regarding the title: we should simply remove it, because the title should only be set in the top left corner of the editor.

The other two properties should be synced, I agree.

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/ddbc551bea980845fc543612706afc1bfb709491
