### ISSUE TITLE
Quill embed video popup incorrectly shown

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#124]
The popup somehow ends up too far left and is partly hidden

**Comment by frogg** [comment]
Same goes also for inserting urls:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/5204169/42626514-ce9db21a-85ca-11e8-942a-07b3009a9900.png">

**Comment by frogg** [comment]
Apparently this has been fixed a while ago:
https://github.com/quilljs/quill/issues/360

According to the package.json were using the latest version 1.3.6 🤷🏼‍♂️
