### ISSUE TITLE
Crash on my profile page

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#133]
When I go to /user/ I get this crash:

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/5204169/42630454-17a9f80e-85d7-11e8-8c06-87f049d75da4.png">

**Comment by RobZuazua** [comment]
Ill take this one

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/84a65142d1d5d2ac88deb88003a02df7fc4802b2
