### ISSUE TITLE
Hypervideo renderer should disable video while popup is shown

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#139]
Otherwise the user can continue playing the video and the quiz will just disappear

**Comment by frogg** [comment]
right now the video is only paused. 
so should the user be forced to take the quiz?
what's the point of #140 then?

**Comment by dlrenz** [comment]
The way this is usually implemented on MOOCs is that you have full control over the part of the video before the next quiz. then you are forced to take the quiz, and afterwards the next part of the video is enabled. If that seems to difficult with the current code, we might have to reconsider it, and cut the video into pieces. But I think in general this functionality makes a lot of sense to me.
