### ISSUE TITLE
Need to API call getAllContentsForCreator

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#142]
Make new API call just like getAllContentsForUser, only that it aggregates all contents from the user who made them (getAllContentsForCreator?). This will be used for creator analytics, so they can see how many people accessed their contents, how much time they spent on average, and so on.

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Backend/commit/28fc10b8e0b5a3e206658d7ee48f724238b073ca 

/getAllContentsForCreator/daniel
