### ISSUE TITLE
game gets cut off 

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#144]
<img width="709" alt="screen shot 2018-07-12 at 11 04 34 am" src="https://user-images.githubusercontent.com/8992275/42645369-6fab0106-85c3-11e8-9d3f-d305dff1fbd0.png">

**Comment by cocokiri** [comment]
Is this later in ContentView after publish?
Can't replicate atm.

**Comment by cocokiri** [comment]
#201 -> similar issue
