### ISSUE TITLE
how does uploading games work?

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#146]
<img width="625" alt="screen shot 2018-07-12 at 1 04 44 pm" src="https://user-images.githubusercontent.com/8992275/42651157-340a645a-85d4-11e8-936d-5678d008c3a7.png">
It does not seem very clear in this picture what this is for

**Comment by cocokiri** [comment]
yep. Where in the backend can I upload my /soundman folder etc? 
Also I will try to make an endpoint for gameUploads

**Comment by frogg** [comment]
@cocokiri 
our digital ocean server doesn't have any Apache or whatever running rn
only nodeJS & express
