### ISSUE TITLE
While learning content, clicking next/prev should update the URL such that I remain at current slide when hitting refresh

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#147]

**Comment by frogg** [comment]
I really like this idea.

**Comment by cocokiri** [comment]
k so the url has to know the currentlSlide  in the params eg
drwho/heat/2

**Comment by dlrenz** [comment]
... and does the current state somehow get saved? I guess we need cookies for that?

**Comment by frogg** [comment]
@dlrenz in the best case we would store this information (progress) in the backend. 
So user can continue on a different device where they left off.

**Comment by frogg** [comment]
this could also be fixed by #252
