### ISSUE TITLE
Comments should be displayed in reverse order

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#149]
That will resolve multiple issues, like not seeing immediately my own new comment

**Comment by RobZuazua** [comment]
hahahah oops

**Comment by RobZuazua** [comment]
not sure who, but someone fixed this already (maybe me) idk

**Comment by dlrenz** [comment]
I did, but since I could not test it, I was not sure if it worked ;)
