### ISSUE TITLE
Make the editor beautiful

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#15]

**Comment by frogg** [comment]
blocked by #31

**Comment by frogg** [comment]
#31 fixed ✅

Todo to make it beautiful:

- remove the border around QuillJS (as described in #34)
- make game editor nice. this is very complicated and looks ugly

**Comment by dlrenz** [comment]
this is too complicate as an issue by itself. closing it for now
