### ISSUE TITLE
Add local git email to GitHub account

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#153]
Otherwise commits of @cocokiri are not linked to his account:

<img width="340" alt="image" src="https://user-images.githubusercontent.com/5204169/42693929-f6d327b0-86b0-11e8-8aa0-2100b8c7f0fc.png">

<img width="391" alt="image" src="https://user-images.githubusercontent.com/5204169/42694036-494d2f54-86b1-11e8-9946-e2d0a4b145b8.png">

1. Run `git config user.email`
2. Then go to GitHub —> Settings —> Emails
3. Add email address form 1.

**Comment by cocokiri** [comment]
![screen shot 2018-07-17 at 12 47 33 pm](https://user-images.githubusercontent.com/3579138/42812976-9e3e1ecc-89bf-11e8-8f59-3f0e6c1d85ba.png)

I don't get it

**Comment by cocokiri** [comment]
should it be another address?

**Comment by frogg** [comment]
which email shows up if you run `git config user.email` in your terminal? the same one?

also, not sure if you want to post your email address here publicly 🙃

**Comment by cocokiri** [comment]
done
