### ISSUE TITLE
fox is hidden in content view

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#163]
<img width="200" alt="screen shot 2018-07-16 at 12 10 34 pm" src="https://user-images.githubusercontent.com/8992275/42772874-51491c26-88f1-11e8-84f3-4a1be718cda3.png">

**Comment by cocokiri** [comment]
His head is above the Buttons now. So it looks like he is hiding behind a fence --> cool
