### ISSUE TITLE
When clicking "View Comments" in ContentSelection, the new page opens, but comments are not displayed

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#168]
The content "work" has a couple comments attached to it, but they only show on the last page in ContentView, not if I click "View Comments" in ContentSelection

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/1ef965beec42b33589d38e498b4946cb5cc8f79a
