### ISSUE TITLE
image cut off and comment button not visible

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#169]
http://localhost:3000/user/f2/old%20photo%20test

![image](https://user-images.githubusercontent.com/5204169/42823158-252b5630-89dd-11e8-8706-8c97e1124f40.png)

**Comment by RobZuazua** [comment]
yea omg the styling is fucked on our site. we need someone to seriously take control of this. @cocokiri it seems like you have been doing it thus far but if you take on this task, youll probably need to put in a little more time to it

**Comment by dlrenz** [comment]
I started doing a lot of small UI improvements today, but will not be able to fix all of them myself, that's for sure ;)

**Comment by dlrenz** [comment]
is this solved? seems like it to me

**Comment by frogg** [comment]
no 
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/5204169/43064418-208d4a3a-8e5f-11e8-8cc8-2957b6f042e7.png">

**Comment by cocokiri** [comment]
@RobZuazua I haven't taken on this task at all. I just get style issues assigned for some reason

**Comment by frogg** [comment]
images still appear to be cut off some times

![image](https://user-images.githubusercontent.com/5204169/43321134-3b5d2e1c-91ab-11e8-8f6f-5a23a08f3012.png)
