### ISSUE TITLE
Enable rating component for content previews and show it after content is consumed

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#17]

**Comment by dlrenz** [comment]
In the SlidesThumbnailView, render small previews of each slide instead of meaningless slide texts "Quiz", "Game" and "Slide"

**Comment by frogg** [comment]
see 5d1660ce88afe6d95adadf8158e34881f22a8d32
that should include this

**Comment by frogg** [comment]
this is for the Learner Frontend @RobZuazua
