### ISSUE TITLE
Publishing / Saving draft needs prompts for user information

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#172]
Published contents can be seen by everyone. When I open my published content, edit it, and hit "save draft", it will disappear from my published contents. This is good behavior, but the user should receive a warning "this content is currently published. Saving it as a draft, will remove it from your published contents."

**Comment by RobZuazua** [comment]
haha i can definitely do this. But is it in the spirit of the 80/20 rule? is this the best use of my time now?

**Comment by dlrenz** [comment]
this is not top priority, but nice to have, as it adds to user flow

**Comment by frogg** [comment]
The whole draft / publish thing is confusing to me anyway. we need to talk about this.
