### ISSUE TITLE
Changing published content apparently does not need further review by us?

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#173]
I can directly edit my published content, and publish the edited version - but that directly appears on the front page, so this mechanism circumvents our "we have to review" the content policy

**Comment by RobZuazua** [comment]
this is a big issue. We will need to have a big clal and talk about design choices and identify all similar issues once we upgrade our app to account for security

**Comment by frogg** [comment]
related to #90 
I know how to fix this, but it requires changes in frontend and backend whenever something is submitted
