### ISSUE TITLE
In editor, clicking open, then escape results in error

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#178]
TypeError: Cannot read property 'onClose' of undefined
handleClose [as onClose]
src/OpenContentDialog.js:43
  40 | }
  41 | 
  42 | handleClose() {
> 43 | 	this.props.onClose(null);
  44 | };
  45 | 
  46 | didSelectContent(selectedContent) {

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/dd51090bf165b75b0a0c7731b4a6153c962de37b
