### ISSUE TITLE
Remix does not work

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#182]
when I click on remix the editor opens but nothing is loaded

**Comment by frogg** [comment]
Probably related to:
https://joinoasys.slack.com/archives/CBL5Q7EJV/p1531861845000080

**Comment by dlrenz** [comment]
Hm. This worked yesterday.
I cannot open the link above - what is this related to?

**Comment by frogg** [comment]
@dlrenz it's your slack message regarding opening contents

Thanks for the fix
