### ISSUE TITLE
👍 use emojis to rate content 👍

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#185]
let users rate content with emoji buttons instead of stars.
this can give very interesting feedback.

potential problem: different users have different understandings what en emoji means.
so we have to choose very clear ones.

🙂 🙁 😭 😡 👍 👎 👩‍🔬

**Comment by dlrenz** [comment]
I support this only if emojis map to some metric
so three degrees of happy emojis, and three degrees of angry emojis would map to:
happiness \in [1,3]
angriness \in [1,3]

**Comment by frogg** [comment]
Here are some more examples:

🙂 😐 😕 🙁 ☹️
🙂 😡 🤬 🤢 🤮

**Comment by dlrenz** [comment]
We could use the normal 5-star rating but replace the stars with emojis:
https://www.presentermedia.com/powerpoint-templates/templates/face-emoji-rating-toolkit/20265-ppt.html

And then use someoptional  additional emojis expressing anger similar to what Facebook is doing:
https://splinternews.com/facebook-uber-are-rolling-out-emoji-based-ratings-on-1793853663

**Comment by cocokiri** [comment]
yah emojis is the way to go
