### ISSUE TITLE
Featured <> Recently Added

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#191]
Switch between featured content and recently added content on the main page

this also requires a new backend API for recently added

**Comment by frogg** [comment]
I'd add a category selection:

- Featured
- New Content
- Physics
- Chemistry
- Computer Science
- …

**Comment by dlrenz** [comment]
Do you mean that you have already implemented it? If so, I do not see it

**Comment by frogg** [comment]
Haha no that’s why I said I *would* do it like this… 😂
I can do it. But first I wanted to know y‘alls opinion
