### ISSUE TITLE
Make Slide View on left side look nicer

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#194]
something like keynote would be good:
<img width="142" alt="image" src="https://user-images.githubusercontent.com/5204169/42888089-c0db9534-8aa7-11e8-98f7-fc412f1554ba.png">

**Comment by dlrenz** [comment]
https://visme.co have a great design, too

**Comment by frogg** [comment]
@dlrenz looks excellent 👍

**Comment by dlrenz** [comment]
yes. designer person should be the first hire :)
