### ISSUE TITLE
When I try to create two Quill Slides in a row (after coming to /create) it deletes one slide instantly

### ISSUE THREAD

**Issue by cocokiri** [OasysFoundation/Oasys-Toolbox-React#200]

**Comment by dlrenz** [comment]
weirdest thing i have come across so far. if i replace
"let slides = this.state.slides.slice();"
with 
"let slides = this.state.slides;"
in function "onAddNewSlide", then the error disappears.

From what I understand, the former should be the correct solution....?!
What gives

**Comment by frogg** [comment]
I dont see a reason for copying the array here anyway.

**Comment by dlrenz** [comment]
if you do not copy than modification of slides is equivalent to modification of this.state.slides, but directly modifying state is discouraged as it can apparently produce unpredictable behavior.
but well... as long as it works ;-)

**Comment by dlrenz** [comment]
ok so we are now (unsafely) modifying the array directly, but it seems to work. I mark this as resolved for now.
