### ISSUE TITLE
Swipeable views inside ContentView cuts of Simulation Iframe because it's fixed 640px

### ISSUE THREAD

**Issue by cocokiri** [OasysFoundation/Oasys-Toolbox-React#201]
![screen shot 2018-07-18 at 5 25 22 pm](https://user-images.githubusercontent.com/3579138/42894681-c80a9570-8ab7-11e8-9630-72e48802016c.png)

**Comment by cocokiri** [comment]
just found an elegant solution thankfully

**Comment by dlrenz** [comment]
what's the solution?
