### ISSUE TITLE
Content with spaces in title shouldn't be saved as %20%

### ISSUE THREAD

**Issue by cocokiri** [OasysFoundation/Oasys-Toolbox-React#204]
![screen shot 2018-07-18 at 9 40 34 pm](https://user-images.githubusercontent.com/3579138/42903844-63555cfc-8ad3-11e8-8152-c284697ba4fd.png)

**Comment by RobZuazua** [comment]
lol , on it

**Comment by RobZuazua** [comment]
They are not saved like that. this is how the frontend is reading the data.

**Comment by RobZuazua** [comment]
ill fix

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/916e87716dea5d1d738c5404a73a9a873ae5247a
