### ISSUE TITLE
Save complete STATE of Editor inside SessionStorage instead of React state

### ISSUE THREAD

**Issue by cocokiri** [OasysFoundation/Oasys-Toolbox-React#206]
It's safer, can be reloaded when he restarts browser and more performant

**Comment by cocokiri** [comment]
only prob is if two people are logged in on the same device...but not a biggy

**Comment by dlrenz** [comment]
great! i do not think we need to support more than one person per device in the foreseeable future :)

**Comment by cocokiri** [comment]
ok since the Thumbnail component got updated, the performance isn't so bad
Will refactor with bigger refactors coming later this month
