### ISSUE TITLE
graphing tool not working

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#209]
<img width="471" alt="screen shot 2018-07-18 at 5 25 25 pm" src="https://user-images.githubusercontent.com/8992275/42908685-9c8ba87e-8aaf-11e8-9462-0a1abd671cca.png">

**Comment by dlrenz** [comment]
This was working earlier today. Will check tomorrow

**Comment by dlrenz** [comment]
fixed
