### ISSUE TITLE
someone broke commenting again

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#210]
<img width="1280" alt="screen shot 2018-07-18 at 5 44 42 pm" src="https://user-images.githubusercontent.com/8992275/42909492-58822f42-8ab2-11e8-8f6e-b8c4b321297c.png">

**Comment by cocokiri** [comment]
mhh I refactored contentView and encapsulated the comments rendering (from 50 lines to 8), but it worked when I tried it
I'll check again today

**Comment by cocokiri** [comment]
![screen shot 2018-07-19 at 10 05 29 am](https://user-images.githubusercontent.com/3579138/42929784-608733a2-8b3b-11e8-82cc-9d93141c64ac.png)

Couldn't find the bug until I realized there was no bug (on localhost)
we need to push the newest swag to firebase
