### ISSUE TITLE
put our website header background on app header as well

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#212]
this is quite boring:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5204169/42910196-defab34e-8ae6-11e8-9d0c-918db9287fa2.png">

this is more exiting:
![oasys_bg_cropped](https://user-images.githubusercontent.com/5204169/42910212-f0ea71c0-8ae6-11e8-8457-cd7e01fb9809.gif)

**Comment by RobZuazua** [comment]
I dont necessarily like the app header here. Can we do any redesign instead of changing background image?

**Comment by dlrenz** [comment]
I agree, this doesn't really work as background image, because content would be barely visible

**Comment by frogg** [comment]
Yeah but we can tint it or make it more transparent, like on Oasys main webpage.
