### ISSUE TITLE
ContentView: Authuser is null

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#219]
![screen shot 2018-07-19 at 18 07 13](https://user-images.githubusercontent.com/5204169/42955820-a7948efa-8b7e-11e8-83c8-e06be0132de8.png)

somewhere here?
```
        var saveEndpoint = 'https://api.joinoasys.org/saveUserContentAccess';
        var data = {
            "accessTimes": timeObj.timing,
            "startTime": timeObj.startTime,
            "endTime": timeObj.endTime,
            "contentId": this.state.content.contentId,
            "accessUserId": this.props.authUser.displayName,
            "contentUserId": this.state.content.userId
        }
```

context: I was looking at a content and clicked on next two times then this happend

**Comment by dlrenz** [comment]
This is not reproducable. 
Has to do either with Feddie's system, or user, or both.

**Comment by frogg** [comment]
same system, different user: cannot reproduce. closing now.
