### ISSUE TITLE
Add "remix" button

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#22]
<img width="339" alt="image" src="https://user-images.githubusercontent.com/5204169/41687474-b3eb7716-749c-11e8-928b-a13bd4dae597.png">

this should open the editor with a clone of this content

**Comment by RobZuazua** [comment]
good idea!

**Comment by frogg** [comment]
mockup:
<img width="332" alt="image" src="https://user-images.githubusercontent.com/5204169/42099872-edaa8cd4-7bbe-11e8-952f-f20399f30f6e.png">

**Comment by frogg** [comment]
Assigned to @cocokiri because it's very similar to #91

**Comment by dlrenz** [comment]
Not sure how the routing works here:
On clicking remix, the url "/create" is being opened, and the state "/user/username/contentname" is forwarded. Somehow, this causes the router to briefly go to "/create", but then right afterwards to "/user/username/contentname".
What should instead happen:
Go to "/create" and run function "onLoad" with the passed state.

**Comment by dlrenz** [comment]
On second thought - maybe it would be better to change "remix" to "bookmark", then hitting "bookmark" would simply add the content to your bookmarks (new backend feature).
In the editor, clicking "open" should only display your own contents and the ones that you bookmarked.
How does that sound?

**Comment by frogg** [comment]
OK so here’s what I would do: I would to go to create/user/content ID and then extract that information and loaded into the editor

**Comment by frogg** [comment]
Works.
