### ISSUE TITLE
change order of slides in editor

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#222]

**Comment by frogg** [comment]
this actually works.

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/107000412cc82b68b756f7ebe2eced8f6786489d

**Comment by RobZuazua** [comment]
i didnt know about the drag bar. i changed it so whole slide has drag functionality

**Comment by dlrenz** [comment]
Cool, that's even better - so we can get rid of the handle bar now

**Comment by frogg** [comment]
Ah wow nice then ignore my previous comment . We wanted to have this anyway. I love it!
