### ISSUE TITLE
Define best practices and guideline checklist and refactor components accordingly

### ISSUE THREAD

**Issue by cocokiri** [OasysFoundation/Oasys-Toolbox-React#225]
When starting next week's BIG refactor

**Comment by dlrenz** [comment]
more info please?

**Comment by dlrenz** [comment]
I don't think refactoring is that easy... but yes some minimal guidelines would be great, especially in terms of variable naming and commenting.

I had another idea, which will help with code quality and refactoring: I'd love it if we dedicated some time (30 minutes?) each day where people can bring up code-related issues, e.g.: which issues took them a long time to solve, which tricks did they learn, which advanced concepts are important for us, etc. Then we can all exchange ideas/knowledge and improve our code ninja level ;)
