### ISSUE TITLE
Thumbnails should be computed in their own pseudo-thread

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#226]
The user experience is dramatically reduced by having to wait for thumbnail generation. 
But this could be done in the background using web workers (JS emulation of threading).
However, trying to use web workers with webpack for me does not work. I tried this:
https://github.com/webpack-contrib/worker-loader

As far as I can tell, this SHOULD work?

**Comment by frogg** [comment]
I noticed that there are some “service workers” being started in the index.js. Is that somehow related? I definitely can take a look into this. It would surprise me if there wasn’t an npm packet for this kind of task. Seems to be something that many people need. But then also, do javascript programmers care about performance and asynchronousity?

**Comment by dlrenz** [comment]
The link that I pasted above references an NPM package that reportedly works fine.
I simply cannot make it run here - so yeah, I'd be happy if you could try.

I read these articles:
https://medium.com/@schreiaj/using-web-workers-react-and-webpack-d2773e3f362d
https://www.experoinc.com/post/getting-started-with-web-workers-via-webpack
