### ISSUE TITLE
Need to change publish / draft behavior

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#227]
Currently, the distinction between publish and draft creates problems in the editor.
It prevents auto-saves (see #186), but there are other problems, too. 
For example, when I open a published content, I would need to unpublish it first before being able to edit.

One possibility is this:
a) published contents can only be remixed, but not simply opened (even by their creators)
b) creators can go to their user page and selectively publish / unpublish contents there. They can also see which of their contents are drafts, in review (published but not accepted by Oasys), rejected (published and denied by Oasys), and published (published and accepted by Oasys)
c) the open dialog in the editor shows (i) unpublished drafts for opening, (ii) published contents for remixing, (iii) bookmarked contents from other users for remixing. (ii) and (iii) can be implemented later
d) editor can save opened draft in the background during editing (since only drafts can be open in the editor now)
e) editor may retain functionality for publishing, but after publish has been clicked, the editor must close the content as it is not editable any more.

**Comment by dlrenz** [comment]
To elaborate further on the above, these would be the things to do for first stage:
a) published contents can only be remixed, but not simply opened (even by their creators)
--> need new API call that only returns my drafts
--> editor open dialog calls this method
b) creators can go to their user page and selectively publish / unpublish contents there. They can also see which of their contents are drafts, in review (published but not accepted by Oasys), rejected (published and denied by Oasys), and published (published and accepted by Oasys)
--> need a new API call "request to publish/unpublish content"
-----> At a later stage, need new db field for accepted/rejected, and some way for us to see which contents are still pending to be accepted
c) the open dialog in the editor shows (i) unpublished drafts for opening, (ii) published contents for remixing, (iii) bookmarked contents from other users for remixing. (ii) and (iii) can be implemented later
--> need to change editor open behavior for non-drafts (remix instead of open)
-----> At a later stage, (ii) and (iii)
d) editor can save opened draft in the background during editing (since only drafts can be open in the editor now)
--> Add editor auto-save as pseudo-thread using javascript workers
e) editor may retain functionality for publishing, but after publish has been clicked, the editor must close the content as it is not editable any more.
--> after hitting publish, forward the user to their user page

Any feedback on this?

**Comment by cocokiri** [comment]
Agree.
about a) you mean they I as creator can't open but remix. If I remix my content and then republish with the same title, then the original content should be updated, right?

**Comment by dlrenz** [comment]
hmm. i think that might be confusing. After clicking on remix, the content should load into the editor with a new id, so that even if I save it immediately with the same title it is in fact a new content. That of course begs the question if I should be allowed to save two contents with the same title.... probably not?

The only way to actually edit my published content itself (without creating a copy of it) would be to unpublish it, edit it, and then publish it again.

**Comment by RobZuazua** [comment]
there was too much information to fully understand what to do here. lets talk about this tomorrow

**Comment by frogg** [comment]
b) i is my favorite so far. Maybe make it more clear: content that has been submitted to us will be reviewed and then released. Once it has been released a user can still edit it. But for the changes to become visible they need to be reviewed as well. It’s like an app update. 
c)

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/1bc1867c7394365ea0 https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/fcf18fa09a63ee658d98e3f2f2314bf508865da85730799f5933cab4928591 https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/d00485555deb6c0ea249115431695d44bcaf8182

**Comment by RobZuazua** [comment]
last frontend : https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/83e6e0b112667b330e61df00dd3d975dfd3cb879

backend: https://github.com/OasysFoundation/Oasys-Backend/commit/84d8050438ec1109b068c4be6ad5b28ee130cd08
