### ISSUE TITLE
Let user delete their Comments

### ISSUE THREAD

**Issue by cocokiri** [OasysFoundation/Oasys-Toolbox-React#231]

**Comment by dlrenz** [comment]
I'm unsure about this... isn't the standard behavior that comments cannot be deleted?

**Comment by RobZuazua** [comment]
I agree with markus here. i think users should be able to delete their comments. This is how it works on facebook and youtube

**Comment by dlrenz** [comment]
ok sure

**Comment by frogg** [comment]
It’s not critical though.
