### ISSUE TITLE
Space between icon and button text is too big

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#236]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/5204169/43080179-60318c16-8e8f-11e8-9b4b-f0e91b619eaf.png">

**Comment by RobZuazua** [comment]
ok! i actually alrady decreased it from 7px to 5px. will decrease to 3px!

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/c99f283e0bbaa7d6c6b8a45ecc06bdbe056d2cb1
