### ISSUE TITLE
First time page loads from website, it is blank. 

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#237]
Im guessing that somewhere we are not handling props or state correctly.

Some element we expect to be there in order for main page to load is not being loaded at the right time and this causes rendering to be empty.

**Comment by frogg** [comment]
Is there anything in the console?
We’ve had this before. I though I fixed it a few weeks ago. #81

**Comment by RobZuazua** [comment]
I cant figure out how to re-produce it.  Its about once every 10 times and no error in console

**Comment by frogg** [comment]
Here's some more background (could not reproduce in safari, but in firefox): 

The <root> tag is empty:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/5204169/43124322-1f8081d4-8f27-11e8-9523-081c8f2cab91.png">


And there are two messages in console (not sure if related though):
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/5204169/43124334-2a28cfce-8f27-11e8-9abb-2917c4c8cf53.png">

**Comment by RobZuazua** [comment]
"expected expression, got <" sounds like a json parsing issue. Maybe somewhere there was html returned where the program expected json. We can try logging output of fetch calls to see where this occured

**Comment by frogg** [comment]
I am still seeing this every now and then. Just now it happened in Firefox on death.joinoasys.org
