### ISSUE TITLE
navbar: only text is clickable

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#238]
clicking on the icon should have the same effect as clicking on the text
(icon should be part of button)
<img width="541" alt="image" src="https://user-images.githubusercontent.com/5204169/43126283-8ea53d70-8f2c-11e8-80f9-bdba79ca33ba.png">

**Comment by RobZuazua** [comment]
i can fix that!

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/7adbcc4b1dad91f2d37509ef46b9c70932e08bb1
