### ISSUE TITLE
Make editor use the full space

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#24]
why is editor so small?
<img width="911" alt="image" src="https://user-images.githubusercontent.com/5204169/41687543-fb211258-749c-11e8-9e64-e57676d9afa0.png">

**Comment by dlrenz** [comment]
Editor should have a reasonable max width - nobody wants to read text if lines have 100+ characters in them.

**Comment by frogg** [comment]
Good point. I was only referring to the small height here originally but the width should definitely be capped.
