### ISSUE TITLE
Rename Open to "Import"?

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#240]
Import would make more sense then we dont need this confusing message anymore
<img width="588" alt="image" src="https://user-images.githubusercontent.com/5204169/43134754-5ea589e2-8f43-11e8-90d6-aa8fbc25443d.png">

**Comment by RobZuazua** [comment]
will discuss in todays meeting

**Comment by frogg** [comment]
Outcome: removing button at all. No need to rename it anymore.
