### ISSUE TITLE
Remove %20 from url

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#241]

**Comment by RobZuazua** [comment]
so whenever this happens:

var username = "dr who"
var title = "this title"
var link = "https://app.joinoasys.org/" + username + "/" + title

if we then redirect to link, the url is now "https://app.joinoasys.org/dr%20who/this%20title"

When the params are read, this happens:
username = "dr who"
title = "this title"

**Comment by RobZuazua** [comment]
if we want: "https://app.joinoasys.org/dr-who/this-title"
a) disallow hyphens in usernames and titles.
b) link.replace(' ', '-')
c) upon consuming, we do link.replace('-',' ')

Any other ideas?

**Comment by dlrenz** [comment]
I think that is good!
We can simply define functions unwrapTitle and unwrapUsername that should be called whenever replacement needs to be done.

**Comment by RobZuazua** [comment]
ok. i am going to do the easier tasks now and post bigger design ideas in github issues so that at least 1 more person can agree before i spend time doing this

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/a5503bbfd92e04a5e11d06821620a91b9d65ee1a
