### ISSUE TITLE
wallet link wrong on user page

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#243]
go to /wallet not /user/wallet

**Comment by RobZuazua** [comment]
<img width="1276" alt="screen shot 2018-07-24 at 9 21 17 am" src="https://user-images.githubusercontent.com/8992275/43144540-03ede8d4-8f23-11e8-9a62-ecd0e2fbea0a.png">

**Comment by frogg** [comment]
fixed in ba3b9503368d237ab53f0879b93f4f3d3c2b0a43
