### ISSUE TITLE
Make Create Page feel more friendly and professional

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#246]
When I click "Create", 

1) Two navbars one under the other looks ugly
2) INSPIRE ME IMMIDIATELY! 
- Why is this editor badass? Maybe have giffs of the highlights of each of the possible slide types instantly come up and then prompt a user to choose one to get started. 
- Make it easy to get them started

**Comment by frogg** [comment]
related to #251
