### ISSUE TITLE
smart defaults in ui

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#251]

**Comment by frogg** [comment]
can you be more specific on this, where and what smart defaults to choose?

**Comment by RobZuazua** [comment]
When you hit create, you should:

1) not have to click "add slide" to get started since 50% of people wont even do that
2) see all the possibility of the editor right away so that you get excited to create something
3) already be prompted with a next button or choose slide button so people get started
