### ISSUE TITLE
Somehow I was able to submit a content without tags and title

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#257]
I submitted a content and somehow it ended up without title and tags in the backend so now the frontend is crashing.

We should make
1. sure that the frontend does not crash.
2. sure that all data is entered when submitting.

![image](https://user-images.githubusercontent.com/5204169/43320215-fc6bbeec-91a7-11e8-823d-6b3cb07821b1.png)

**Comment by frogg** [comment]
Reproducing the crash:
https://death.joinoasys.org/user/frederik/

**Comment by RobZuazua** [comment]
how did you do this? right now submit button is only allowed if this fields are empty

**Comment by frogg** [comment]
I am not sure how I did this, but it happened.
The backend should probably also reject incomplete contents when submitted?

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Backend/commit/e58b0749afbb6043a10eebe8dad5a68751706797
