### ISSUE TITLE
"Create your own content!" Button looks weirdly big

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#267]
Is that intentional to get more attention?

<img width="475" alt="image" src="https://user-images.githubusercontent.com/5204169/44155219-00ec88d4-a0ad-11e8-9c03-41d8691529c7.png">

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/c7aa0027390975402120bb014df9234b090d9f1b
