### ISSUE TITLE
Add "Featured Experiences" to "Popular Topics"?

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#268]
When clicking through a few popular topics they will push down the featured section to the bottom.
It would be good to bring it back to the top I think.

<img width="953" alt="image" src="https://user-images.githubusercontent.com/5204169/44155389-6f3850c0-a0ad-11e8-88cb-09836f698633.png">

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/ef2e21c5c7c15bec8e464f8c1082d2c40a1bf5d3
