### ISSUE TITLE
What are the colors selecting the popular topics?

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#269]
<img width="122" alt="image" src="https://user-images.githubusercontent.com/5204169/44155703-4ca422e0-a0ae-11e8-82a1-362f14e712c3.png">

I am referring to the line under "Mathematics".
Is this color symbolizing something? Or can we use the same selection color for all topics?

**Comment by dlrenz** [comment]
Maybe just change border collie instead of having the line?

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/e7b978e99aa15e3ab4a54b3e86b4a87118e4b65e ??

**Comment by RobZuazua** [comment]
this works for me.
