### ISSUE TITLE
Arrow Icon is missing on the right side of "Featured Experiences"

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#270]
<img width="973" alt="image" src="https://user-images.githubusercontent.com/5204169/44155784-7c19e852-a0ae-11e8-96e1-685613ad7492.png">

This is on page load. When I click on the invisible button or scroll with the trackpad, the arrow will appear.

**Comment by RobZuazua** [comment]
Does this always happen? I cannot seem to reproduce it but it happens randomly every once and a while for me

**Comment by frogg** [comment]
Yep, I can reproduce this always.

**Comment by frogg** [comment]
yep this is not reproducible anymore. thanks for fixing!
