### ISSUE TITLE
Category Name: "iOs" —> "iOS"

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#271]
<img width="103" alt="image" src="https://user-images.githubusercontent.com/5204169/44155925-dac95068-a0ae-11e8-8b77-b47687f2edeb.png">

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/6471e981cb7bc8e8bb2dedb8e68990f3e8dc9584
