### ISSUE TITLE
Use Daniel's NavBar?

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#273]
I dont like colored icons in the nav bar…for that reason I like Daniel's more (at least the right half).

Yours of course is gorgeous on the left half with the search bar…so maybe merge them? 😃 

<img width="258" alt="image" src="https://user-images.githubusercontent.com/5204169/44156224-b49f8244-a0af-11e8-9cdf-21d4934c3d02.png">

<img width="528" alt="image" src="https://user-images.githubusercontent.com/5204169/44156287-de88ea28-a0af-11e8-8408-8d5f76b2426d.png">

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/7beae9a3f95813a558a97f51a4bf5ad8f6ee6ea2
