### ISSUE TITLE
"Select" is a strange title for a Search bar 🤔

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#277]
<img width="527" alt="image" src="https://user-images.githubusercontent.com/5204169/44156689-cdb0b928-a0b0-11e8-8649-554079e8cd8f.png">

Maybe just label it "Search…" (yeah I know it is also a selection, but this is how it works on facebook as well)

<img width="506" alt="image" src="https://user-images.githubusercontent.com/5204169/44156733-ea0243e4-a0b0-11e8-8e16-ae8a7fe56c16.png">

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/1771735561f9ae79a92d06bbb8936d8df6a54219
