### ISSUE TITLE
what is the difference between forgot password – reset password?

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#282]
<img width="353" alt="image" src="https://user-images.githubusercontent.com/5204169/44408321-726d2880-a560-11e8-8389-7144726c95a3.png">

**Comment by RobZuazua** [comment]
reset password you can do with your credentials without leaving site. Forgot password allows you to change password with email. 

Is this confusing? Maybe we only allow forgot password

**Comment by frogg** [comment]
I think we should remove 'reset password' here.
It's basically to set a new password right? We could move this functionality to the user account page then.

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/aad41e0bbe45c599cd4d7b6221a8aa4a1bc79f62
