### ISSUE TITLE
logout – create – explore: are those our 3 main capabilities? ;)

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#285]
When you log in this is what you see first.
I think it must be more kick-ass
also, the logout button gets way too much attention!
![image](https://user-images.githubusercontent.com/5204169/44519811-6c955580-a6ce-11e8-9f3d-5e0a0b6c7278.png)

**Comment by dlrenz** [comment]
Where does this appear?

**Comment by frogg** [comment]
account page, right after you logged in

**Comment by dlrenz** [comment]
why is this our account page? it has nothing to do with what we wanted it to be

**Comment by frogg** [comment]
$ git blame not me
