### ISSUE TITLE
account page items should have same left align

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#286]
![screen shot 2018-08-24 at 15 51 56](https://user-images.githubusercontent.com/5204169/44588349-b9a02700-a7b5-11e8-9f92-3ff218ec2608.png)

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/b958b1907cc0cb5dce04e42f0d840f07aac2e6a6
