### ISSUE TITLE
page refresh causes this.props.user to be invalid

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#289]
When I take user from store and display it in componentDidMount, it shows the correct user (me), but after page refresh, all fields (displayName, uid) are null.

Code to reproduc (put in any component that takes user from store):

    componentDidMount() {
    	console.log(this.props.user);
    }

**Comment by RobZuazua** [comment]
i told everyone about this yesterday. i talked about it during our call, plus wrote a summary in slack ![bitmoji](https://render.bitstrips.com/v2/cpanel/757ac79c-3669-42d3-b687-13e66b9ff56f-d8350c36-004c-424b-ac89-f337730d43a0-v1.png?transparent=1&palette=1&width=246)

**Comment by RobZuazua** [comment]
its because of the new way we are doing auth which i really dont like lol

**Comment by frogg** [comment]
is this still relevant? I was able to do the auth dance without problems for the nav bar login button earlier this afternoon
