### ISSUE TITLE
Selecting content on main page while scrolled down

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#290]
The page should automatically scroll up when I select a content from the main page.
Instead, I see this:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/5204169/44657445-1f322480-a9fd-11e8-9940-8d41467b753f.png">

**Comment by dlrenz** [comment]
really, we have to implement this in every single component?
--> HOC

**Comment by dlrenz** [comment]
i implemented a new component that is included by the router. 
it automatically scrolls up every time the url changes
