### ISSUE TITLE
Clicking on "remix" on content intro view goes to /create/undefined/undefined

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#291]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/5204169/44657513-5ef90c00-a9fd-11e8-9b17-0e481255d8ef.png">

http://localhost:3000/create/undefined/undefined

**Comment by dlrenz** [comment]
I guess I am too stupid for this - but still did not understand how we do authentication now

**Comment by dlrenz** [comment]
if every component has to check by itself now --> HOC
