### ISSUE TITLE
Saving or Publishing always results in error message

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#292]
<img width="593" alt="image" src="https://user-images.githubusercontent.com/5204169/44657595-a54e6b00-a9fd-11e8-9875-1aa87aee8d4e.png">

**Comment by frogg** [comment]
From the firefox console:
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.joinoasys.org/save/. (Reason: missing token ‘authorization’ in CORS header ‘Access-Control-Allow-Headers’ from CORS preflight channel).
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://api.joinoasys.org/save/. (Reason: CORS request did not succeed).
```

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Backend/commit/572259ba095822c068988ed2676790d14f44fd06

**Comment by frogg** [comment]
Hmm on localhost and death.joinoasys I still see the error message. Have you deployed the server code?

**Comment by RobZuazua** [comment]
Not deployed on server is the reason

**Comment by frogg** [comment]
backend now pushed, works.
