### ISSUE TITLE
weird selection in topic menu

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#296]
![hmm 2018-08-27 15_55_31](https://user-images.githubusercontent.com/5204169/44663743-aab5b080-aa11-11e8-8da5-069edb54125e.gif)

when I click on the bottom somehow the whole menu bar is selected

**Comment by dlrenz** [comment]
I wanted to change this so the landinpagecontroller's state has the id for the currently selected category. then it can pass it down to horizontalbuttonmaker, which could append a classname for the active id.

However, the implementation is so confusing to me, that I seem unable to do this :-(

**Comment by RobZuazua** [comment]
daniel lets talk about this in our meeting tomorrow

**Comment by frogg** [comment]
This seems to be fixed. I cannot reproduce anymore.
