### ISSUE TITLE
search does not work

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#304]
I searched for 'earth' which clearly exists below
but does not show up in search

![image](https://user-images.githubusercontent.com/5204169/44719603-1bb5a080-aac4-11e8-8369-7f419f8fae7b.png)

**Comment by RobZuazua** [comment]
It searches by tags instead of title right now

**Comment by frogg** [comment]
search for title and author should definitely be added!

**Comment by dlrenz** [comment]
I added search by author and tags
