### ISSUE TITLE
clicking three dots on content tiles in account page yields error

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#305]
TypeError: _this2.props.toggleOpen is not a function

**Comment by frogg** [comment]
Yep I could reproduce. problem: the action sheet that would pop up is implemented in `LandingPageController.js`:

```javascript
<HorizontalScroll key = {dataObj.title} title = {dataObj.title} data = {dataObj.data} type = "mobile" toggleOpen={this.toggleOpen}/ >
```

and

```javascript
    toggleOpen(data) {
        this.setState({
          open: !this.state.open,
          currentTitle: data.title,
          currentUsername: data.username,
          contentId: data.contentId,
          uid: data.uid,
          data: data,
        });
    }
```

Proposed Solution: Move this little popup in its own component:
![image](https://user-images.githubusercontent.com/5204169/44723425-473e8800-aad0-11e8-9c7c-2ec702926941.png)

**Comment by frogg** [comment]
works now
