### ISSUE TITLE
Tables in Text Editor

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#310]
humhub open source social network has an editor with tables
https://github.com/humhub/humhub

<img width="552" alt="image" src="https://user-images.githubusercontent.com/5204169/44737952-b11c5900-aaf3-11e8-990d-ecf81935aec3.png">

**Comment by dlrenz** [comment]
Several text editor support tables, just quill does not currently. It will, though, in the next major release

**Comment by frogg** [comment]
ok then nvmnd
