### ISSUE TITLE
"Open" is empty

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#315]
As you can see from my previous issues this seemed to work. Without any changes I clicked on the open button again. This time strangely with no content:

<img width="528" alt="image" src="https://user-images.githubusercontent.com/5204169/44784697-d0b48f80-ab8e-11e8-8d79-ef15bfbcafe8.png">

**Comment by RobZuazua** [comment]
I wrote about this in the document last night!
