### ISSUE TITLE
incorrect username on content finished page

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#316]
it is always undefined, i think

**Comment by frogg** [comment]
I'll do this one.

**Comment by frogg** [comment]
not only the username is affected, all values used to be undefined.

**Comment by dlrenz** [comment]
This is not fixed.
On another user's content, it shows MY username instead of the other user's username.

**Comment by frogg** [comment]
lol right. now it should work
