### ISSUE TITLE
Wrong link in content tile modal > go to user page

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#322]
This is what I get when I click "got to mark22's page":

![image](https://user-images.githubusercontent.com/3540190/44785747-3f471c80-ab92-11e8-831f-f95e404e48d7.png)

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/d47c9db4c8eca35eeb259db68d66ee3dc8a088e1
