### ISSUE TITLE
Clicking/Tapping on the three dots on content tiles is quite difficult

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#323]
If I tap/click just a few pixels off the three dots, the content opens instead of the modal. 
I suggest putting the dots in an invisble bounding box that stretches ~10 pixels in each direction

**Comment by frogg** [comment]
good idea! 

does this work: `margin: '10px'`?

**Comment by dlrenz** [comment]
padding: '10px' could work depending on where the link is wrapped around.
let me know, i can do this probably in 2 minutes

**Comment by RobZuazua** [comment]
just add some padding and this will work! You may need to add negative margin if the style is acting weirdly. add me to issue if it takes yall more than 5 mins!
