### ISSUE TITLE
contentview does not indicate if new chapter is loading

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#330]
When clicking on next chapter, sometimes an empty page comes up with just the down-arrow on it. Then, seemingly out of nowhere, the elements of the chapter start appearing. This can take several seconds.

**Comment by dlrenz** [comment]
Happens to me all the time with this content:
http://localhost:3000/view/Frederik%20Riedel/Help%20to%20find%20a%20new%20Earth!/Hxo8v5Fu5VO5ZfL3ZShoWdSMA7i1/b93e81ff-a0a4-445d-abd9-58e50fb9bcf0

**Comment by frogg** [comment]
I always used those so far:

http://www.davidhu.io/react-spinners/

**Comment by dlrenz** [comment]
Which one is your favorite?
I like the ring loader, it's something a bit different

**Comment by frogg** [comment]
suggestion from markus: https://github.com/jamiebuilds/react-loadable
