### ISSUE TITLE
Publish does not work

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#332]
The publish button in the settings modal does not do anything, I think

**Comment by RobZuazua** [comment]
@cocokiri

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/a2e1dca0830d3e198f04bb98b8ee68a37ca26fe7 . it worked, it was just unintuitive because it required you to change title. i fixed it up
