### ISSUE TITLE
Re-Organize Routing

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#36]
instead of going directly to app.joinoasys.org/username we should add /u/ or /user/ inbetween – otherwise what happens if a user named /create/ or /explore/ appears on our platform 😬
this helps us to be safe with that in case we need a new /folder/ in the future

Example:

instead of https://app.joinoasys.org/Markus/Soundman
make it https://app.joinoasys.org/user/Markus/Soundman

**Comment by frogg** [comment]
This breaks the "explore" links in the backend

They need to be updated now as well to

`user/Markus/Soundman`

**Comment by cocokiri** [comment]
👍
