### ISSUE TITLE
CORS Bug: Fetch API cannot load http://174.138.2.82/GetContentsPreview 

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#38]
When I open https://app.joinoasys.org/learn no content is loading for me, the console shows this:
`Fetch API cannot load http://174.138.2.82/GetContentsPreview due to access control checks.`

**Comment by RobZuazua** [comment]
main.790aef6f.js:1 Mixed Content: The page at 'https://app.joinoasys.org/learn' was loaded over HTTPS, but requested an insecure resource 'http://174.138.2.82/GetAllContent'

**Comment by RobZuazua** [comment]
Looks like it is because i still havent setup https and when you connected it to our subdomain, it now requires https.

**Comment by frogg** [comment]
Ah yeah we have https on app.joinoasys so the browser prevents to load insecure data (which makes sense because it would destroy the whole purpose of https) 

so after all this is blocked by https://github.com/OasysFoundation/Oasys-Backend/issues/1

**Comment by RobZuazua** [comment]
now https://api.joinoasys.org/{} works. https setup

**Comment by frogg** [comment]
Amazing!
