### ISSUE TITLE
Upload picture 

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#40]
Use the file input Tag in react to allow user to upload an image. 

@frogg I am guessing that the best solution is to then use D.O. Spaces to save the image and return the url for it?

**Comment by frogg** [comment]
Yep I agree. That gives us plenty of space and data transfer speed.

**Comment by RobZuazua** [comment]
Setup Digital Ocean Spaces on my account. Next, need to allow users to upload photos to our spaces account: https://www.digitalocean.com/community/questions/can-i-upload-images-to-spaces-using-node-js

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/743bc514112961e56887b3855b096c04b1c2f01a
