### ISSUE TITLE
Load content in preview mode in editor

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#51]
We have the JSON data from the backend. Now we need to display this in react in two places.

1) When clicking "Open"  in the create tab of the editor
- you have the data from the backend. Now we need to put that data into the quill editor 

2) When you click explore to go to https://app.joinoasys.org/Markus/Soundman. This should load the editor component, then load the data from the backend from https://api.joinoasys.org/Markus/Soundman into the editor in preview mode.

**Comment by dlrenz** [comment]
In editor, I can save a content with username drwho and contentname firstcontent. The HTTP response is OK. Then I try to open that content by clicking Open and inserting "user/drwho/firstcontent" as the link. The response is an OK and contains an empty set of slides for this content. Maybe some error in parsing in the backend?

**Comment by RobZuazua** [comment]
Ill check it out

**Comment by RobZuazua** [comment]
@dlrenz content from backend is now there. You can load it into editor now

**Comment by dlrenz** [comment]
cool. can't check right now unfortunately, as oasys learn and/or the router are broken

**Comment by frogg** [comment]
That works now, right?

https://app.joinoasys.org/user/43/rob12

Can be closed?

**Comment by cocokiri** [comment]
yep
