### ISSUE TITLE
Mobile Bugs

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#56]
Some things here are not accessible from a smartphone at all.
—> #responsivedesign

Navigationbar:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/5204169/42003332-d5e61e4c-7a1f-11e8-9f8c-3c37f13bc130.png">
Editor Sidebar & Menu Bar:
<img width="802" alt="image" src="https://user-images.githubusercontent.com/5204169/42003340-e484d042-7a1f-11e8-926c-05ba88fbc6c9.png">
…

**Comment by RobZuazua** [comment]
This is a big issue that will take someone a lot of time. Let us first finish MVP functionality in web then someone can port it over to be more mobile friendly. (lets aim for next week)

**Comment by cocokiri** [comment]
Yeah no editor on mobile.
Also, anything smaller than an iPad isn't really interactive, so it isn't a good use case.

If you're on mobile we should filter contents to only the text / video / quiz ones. Anything else is a dread no matter how good your responsiveness

**Comment by dlrenz** [comment]
I think this is ok for now
