### ISSUE TITLE
To be discussed: show ContentSelection even when not logged in?

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#61]
right now we send the user straight to the login page when they go to app.joinoasys.org:

```
 <div>
          { this.props.authUser
              ? <ContentSelection/>
              : <LoginPage/>
          }
</div>
```

I think we should still show the ContentSelection page as initial page but maybe with an additional message to sign in / sign up.

**Comment by RobZuazua** [comment]
discussed and completed
