### ISSUE TITLE
setting a new password should require entering the old password first

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#62]
<img width="387" alt="image" src="https://user-images.githubusercontent.com/5204169/42083550-86904a58-7b8b-11e8-93e0-53e7d5e5318c.png">

Set new password:

{Enter old Password}
{Enter new Password}
{Verify new Password}

**Comment by RobZuazua** [comment]
This is what firebase says : 

Some security-sensitive actions—such as deleting an account, setting a primary email address, and changing a password—require that the user has recently signed in. If you perform one of these actions, and the user signed in too long ago, the action fails with an error.

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/712daea7910c947abd553b789d5609e45a58d753
