### ISSUE TITLE
Right after signup the username is not shown

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#65]
When I sign up for the first time I am automatically logged in afterwards.
The problem is that the username is not shown right away. Only when I reload.
This does never happen again. Only on very first initial sign in. 

<img width="533" alt="image" src="https://user-images.githubusercontent.com/5204169/42084930-5d09b0da-7b8f-11e8-831e-91aa5174994e.png">

**Comment by RobZuazua** [comment]
After forever, i finally found the error: https://github.com/firebase/firebase-functions/issues/95. Fixing now!

**Comment by RobZuazua** [comment]
The only fix is Very hacky, so i instead just added a "My profile" text the first time they sign in instead of username. 

The other option is checking if string is null then continuously calling a function until the display name is populated. 

Let me know if this doesnt work. will close now

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/e3a8a0d11561f28e536f8f83f8199c6c828c00cc
