### ISSUE TITLE
Don't publish content right away on main explore page

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#68]
- everyone could post bad content
- only publish on user page right away
- then we select good content to publish on the main page

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Backend/commit/d53abe1136b30a74e3cb09906a7319d065d80cc7

**Comment by RobZuazua** [comment]
Basically we need to do this before to feature something :

db.contents.update({contentId:"Work"},{$set:{featured:true}})
