### ISSUE TITLE
Importing MS Word documents

### ISSUE THREAD

**Issue by dlrenz** [OasysFoundation/Oasys-Toolbox-React#70]
Most starred:
https://github.com/mwilliamson/mammoth.js/
Alternative:
https://github.com/lalalic/docx2html

**Comment by frogg** [comment]
the mammoth.js looks great and also seems to provide api to extract images separately

**Comment by RobZuazua** [comment]
Let's discuss Monday. still not certain there is a use case for this

**Comment by dlrenz** [comment]
I was looking into how to perform OCR on scanned texts, but this appears to be a standard feature in lots of software now, and also in MS Word. That's why I was thinking that we can just allow imports from there
