### ISSUE TITLE
Data Structure: Save username and project name instead of URL

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#76]
I noticed that we only save the URL right now to a project in the JSON (at least that's what's exploded by the server):

```JSON
{
"picture": "mypic",
"title": "firstcontent",
"description": "mydesc",
"tags": "myhash",
"url": "/user/drwho/firstcontent"
}
```

I propose to store the username and content name instead. The URL can be generated from that information: /user/{username}/{project name}

```JSON
{
"picture": "mypic",
"title": "firstcontent",
"description": "mydesc",
"tags": "myhash",
"username": "drwho"
}
```

This is more clean because we store the original data here, not the generated URL. As we already know, the URL can change ;)
Also this makes features like #73 possible.

But let's discuss advantages/disadvantages before implementing!

**Comment by RobZuazua** [comment]
I can do this! you are right :)

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/5df9b809d80fb0d1305b270d5238d2dc49e4d334 https://github.com/OasysFoundation/Oasys-Backend/commit/dbbc1b03299549e73552d90e15471a56cbb90e55
