### ISSUE TITLE
I am signed in but /user refers me to /login

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#78]
<img width="1165" alt="image" src="https://user-images.githubusercontent.com/5204169/42137967-aea9508e-7d75-11e8-93e5-b94dfc96965c.png">

Did my session expire?
In the best case we should prevent that (like facebook, you're always logged in until you log out explicitly). Or is it a bug? My name is still displayed in the top right corner…

Edit:
Ok just verified, it's probably a bug. I signed our and signed in again and still being referred to /login when I go to /user. (in this case my session cannot be timed out)

**Comment by RobZuazua** [comment]
looks like a bug

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/f8382a8440a3997da06024b41353acecc81d1e23
