### ISSUE TITLE
White Page

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#81]
Sometimes when I load app.joinoasys.org all I see is white.
When I reload it fixes itself.
But why?
<img width="1369" alt="screen shot 2018-07-02 at 10 20 56" src="https://user-images.githubusercontent.com/5204169/42152857-b2c882ea-7de1-11e8-937a-92787d79ad61.png">

Maybe @cocokiri has an idea where this comes from?

**Comment by frogg** [comment]
I've never experienced a white page since d13278428a76403d80ba21b9c839e0c5e91655f7

**Comment by dlrenz** [comment]
Probably solved

**Comment by frogg** [comment]
Yep looks like it has been solved 💯
Still could not reproduce it again.
Please re-open if you see it again.
