### ISSUE TITLE
Hyper Video Editor: Pasting Youtube URL crashes whole app

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#86]
So far I could not figure out what's going on here. 🤷🏼‍♂️

<img width="958" alt="image" src="https://user-images.githubusercontent.com/5204169/42184297-563c525e-7e45-11e8-8667-6309fe6e4863.png">

**Comment by dlrenz** [comment]
For me this only happens the first time I'm trying to paste a URL. Reloading the app, it works fine afterwards.

On crash, I get multiple errors but also this warning:
Cross-Origin Read Blocking (CORB) blocked cross-origin response https://www.youtube.com/watch?v=aqFpDpUMt2I with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.

Also, we can try to debug this ourselves by changing "plyr.min.js" to "ply.js" in file "node_modules/plyr/package.json"

**Comment by frogg** [comment]
For me it crashes all the time, even after refreshing with this error message:

```
TypeError: null is not an object (evaluating 'e.split')
mime — plyr.min.js:1:7131
filter
get — plyr.min.js:1:8107
get — plyr.min.js:1:92579
inject — plyr.min.js:1:31454
build — plyr.min.js:1:48151
(anonymous function) — plyr.min.js:1:82558
r — plyr.min.js:1:88559
value — plyr.min.js:1:89255
change — plyr.min.js:1:82128
set — plyr.min.js:1:92804
updateVideoSource — index.js:125
componentDidUpdate — index.js:237
dr — react-dom.production.min.js:219
fr — react-dom.production.min.js:211:214
lr — react-dom.production.min.js:210:277
flushInteractiveUpdates — react-dom.production.min.js:225:440
J — react-dom.production.min.js:44:378
ze — react-dom.production.min.js:89:372
interactiveUpdates — react-dom.production.min.js:225:361
Ve — react-dom.production.min.js:89:113
Ve
```

**Comment by dlrenz** [comment]
Alternatively, we could use react-player component, which works fine for updating URL via state

**Comment by dlrenz** [comment]
I get this error, too. Apparently, the Plyr's mime function crashes, because after trying to evaluate the type "text/html" it decides that this is not supported or something like that. This is how far I came for now

**Comment by frogg** [comment]
The reason for the crash there is because `inputType` is `null` in this line: `var _inputType$split = inputType.split('/'),`
But why is it `null`?

**Comment by dlrenz** [comment]
See above...
More detail: 
In line 779, sources contains only one element which represents the link to the pasted video. It's type is "", which causes the mime function in line 782 to crash.

**Comment by dlrenz** [comment]
Hm. this function does not get called at all whenever pasting actually works

**Comment by dlrenz** [comment]
Maybe it's possible to put the player into a disabled state, where the url can safely be changed? 
The onStateChange function seems to support state -1 "unstarted", but I can't figure out how to set this state via react
