### ISSUE TITLE
usernames are not unique

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#89]
Right now, there can be two people with name drwho

@frogg is that a problem?

**Comment by frogg** [comment]
Is username = userID?

**Comment by frogg** [comment]
@RobZuazua  this could be helpful:
https://stackoverflow.com/a/35244705

**Comment by frogg** [comment]
Update on this:

1. We should stop using firebase displayName. This doesn't support uniqueness.

Now we have two options:
- Use our own database that connects `user.uid` to a unique username.
- Use firebase's real time database to connect `user.uid` to their unique username.

(where `user.uid` is the persistent unique identifier that each account has, for example mine is: `7ePrR7vRsla0T6TIjtILWTWl30Z2`)

**Comment by RobZuazua** [comment]
https://github.com/OasysFoundation/Oasys-Toolbox-React/commit/900b2229090db5bedcd904b2391f734f9442d3cc
