### ISSUE TITLE
Loading Content: Bad Gateway

### ISSUE THREAD

**Issue by frogg** [OasysFoundation/Oasys-Toolbox-React#9]
The app attempts to load content form server:
`const loadContent = 'http://174.138.2.82/GetAllContent';`

(this is in ContentSelection.js)

But this request fails:
```
502 Bad Gateway

nginx/1.10.3 (Ubuntu)
```

**Comment by dlrenz** [comment]
run "npm run build" and then open index.html. that should work. somehow the local server that serves to code on your computer is not correctly configured to do CORS.
