### ISSUE TITLE
Open still doesnt work 

### ISSUE THREAD

**Issue by RobZuazua** [OasysFoundation/Oasys-Toolbox-React#91]
When we click open or remix, the slides still dont show up in editor

**Comment by frogg** [comment]
Yeah, so the content object is made available in `MenuBarView` line 209.

```
closeOpenDialog(selectedContent) {
    console.log("Selected Content: " + selectedContent);
```

from there it has to be propagated to the editor and then it must be loaded from the server and inserted into the editor.
